meta_product_name: "Sprint Awesome"
meta_title: "Sprint Awesome | Sprint visualisation tool for product owners using Trello"
meta_description: "Visually track the progress of your sprints with key metrics: burndown chart, team productivity & individual contributions."
meta_image: "logo.png" # should exist in `app/assets/images/`
